### ISSUE TITLE
calculation edge coverage source code

### ISSUE THREAD

**Issue by makerdd** [psi-func/frida-executor#1]
Thank you very much for your open source project, it is very useful for me.
I have a question about code coverage, is coverage calculation implemented? I can't find the relevant content, can you help me point out the specific implementation location.

**Comment by psi-func** [comment]
Hi, calculating coverage implemented via frida stalker mode dynamic recompilation (edge coverage hitcount map only for x86_64)
https://github.com/psi-func/frida-executor/blob/60b45816f1ad646c2321b84233fc6f94d6e112f8/agent/instrumentor.ts#L68
You can change hash function to avoid collisions in map

**Comment by makerdd** [comment]
Thank you very much for your answer, it is very useful for me.
I try to implement coverage detection for x86 architecture.
